# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0020_auto_20240502_0022'),
        ('work', '0010_auto_20170121_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u8017\u6750\u540d\u79f0')),
                ('type', models.TextField(verbose_name='material type')),
                ('unit', models.CharField(max_length=20, verbose_name='unit of material')),
                ('number', models.IntegerField(default=0, verbose_name='material number')),
                ('left_number', models.IntegerField(default=0, verbose_name='left number')),
                ('price', models.FloatField(default=0.0, verbose_name='\u8017\u6750\u5355\u4ef7')),
                ('total_cost', models.FloatField(default=0.0, verbose_name='total cost')),
                ('asset_type', models.IntegerField(choices=[(1, b'\xe8\x80\x97\xe6\x9d\x90'), (2, b'\xe5\x9b\xba\xe5\xae\x9a\xe8\xb5\x84\xe4\xba\xa7')], default=(1, b'\xe8\x80\x97\xe6\x9d\x90'), verbose_name='asset type')),
            ],
            options={
                'verbose_name': 'material record',
                'verbose_name_plural': 'material records',
            },
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='classroom',
            name='name',
            field=models.CharField(default='hello world', max_length=50, verbose_name='class room name'),
            preserve_default=False,
        ),
    ]
