# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-02 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0011_auto_20240502_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialrecord',
            options={'verbose_name': '\u8d44\u4ea7\u6761\u76ee', 'verbose_name_plural': '\u8d44\u4ea7\u8bb0\u5f55'},
        ),
        migrations.RemoveField(
            model_name='materialrecord',
            name='asset_type',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u5b9e\u8bad\u5ba4\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='left_number',
            field=models.IntegerField(default=0, verbose_name='\u5269\u4f59\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='number',
            field=models.IntegerField(default=0, verbose_name='\u6570\u91cf'),
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='total_cost',
            field=models.FloatField(default=0.0, verbose_name='\u603b\u4ef7'),
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='type',
            field=models.TextField(verbose_name='\u8017\u6750\u89c4\u683c'),
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='\u5355\u4f4d'),
        ),
    ]
