# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-10 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0013_materialrecord_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrecord',
            name='ps',
            field=models.TextField(blank=True, null=True, verbose_name='material ps'),
        ),
        migrations.AddField(
            model_name='materialrecord',
            name='use_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='use instructions'),
        ),
    ]
