# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-10 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0014_auto_20240510_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrecord',
            name='ps',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='materialrecord',
            name='use_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='\u4f7f\u7528\u8bf4\u660e'),
        ),
    ]
