# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-02 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0013_materialrecord_asset_type'),
        ('flow', '0020_auto_20240502_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2024, 5, 2, 16, 34, 40, 798950, tzinfo=utc), verbose_name='add time')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.ClassRoom', verbose_name='add material room number')),
                ('material_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.MaterialRecord', verbose_name='\u8017\u6750\u540d\u79f0')),
            ],
            options={
                'verbose_name': 'add material',
                'verbose_name_plural': 'add material',
            },
        ),
    ]
