# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-03 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0021_addmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 10, 40, 51, 131729, tzinfo=utc), verbose_name='add time'),
        ),
    ]
