# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-03 12:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work', '0013_materialrecord_asset_type'),
        ('flow', '0022_auto_20240503_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyBuyMaterialProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_agree', models.BooleanField(default=False, verbose_name='apply status')),
                ('is_storage', models.BooleanField(default=False, verbose_name='apply status')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='apply time')),
                ('storage_time', models.DateTimeField(auto_now_add=True, verbose_name='storage time')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='applicant')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.ClassRoom', verbose_name='apply material class room number')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.MaterialRecord', verbose_name='\u8017\u6750\u540d\u79f0')),
            ],
            options={
                'verbose_name': 'apply buy material process',
                'verbose_name_plural': 'apply buy material process',
            },
        ),
        migrations.AlterModelOptions(
            name='addmaterial',
            options={'verbose_name': '\u624b\u52a8\u8017\u6750\u5165\u5e93', 'verbose_name_plural': '\u624b\u52a8\u8017\u6750\u5165\u5e93'},
        ),
        migrations.AlterField(
            model_name='addmaterial',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 12, 24, 42, 345723, tzinfo=utc), verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='addmaterial',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.ClassRoom', verbose_name='\u5165\u5e93\u6559\u5ba4'),
        ),
    ]
