# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-03 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0023_auto_20240503_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applybuymaterialprocess',
            old_name='material',
            new_name='material_record',
        ),
        migrations.AlterField(
            model_name='addmaterial',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 12, 42, 17, 914334, tzinfo=utc), verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
    ]
