# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-06 03:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0024_auto_20240503_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applybuymaterialprocess',
            options={'verbose_name': '\u8017\u6750\u8d2d\u4e70\u7533\u8bf7', 'verbose_name_plural': '\u8017\u6750\u8d2d\u4e70\u7533\u8bf7'},
        ),
        migrations.AlterField(
            model_name='addmaterial',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 3, 37, 36, 384361, tzinfo=utc), verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='applybuymaterialprocess',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7533\u8bf7\u4eba'),
        ),
        migrations.AlterField(
            model_name='applybuymaterialprocess',
            name='apply_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='applybuymaterialprocess',
            name='class_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.ClassRoom', verbose_name='\u5b9e\u8bad\u5ba4'),
        ),
        migrations.AlterField(
            model_name='applybuymaterialprocess',
            name='is_agree',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u901a\u8fc7'),
        ),
        migrations.AlterField(
            model_name='applybuymaterialprocess',
            name='is_storage',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5165\u5e93'),
        ),
        migrations.AlterField(
            model_name='applybuymaterialprocess',
            name='storage_time',
            field=models.DateTimeField(default=None, verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
    ]
