# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-06 03:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0025_auto_20240506_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 3, 47, 55, 766535, tzinfo=utc), verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='applybuymaterialprocess',
            name='storage_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
    ]
