# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-10 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0029_auto_20240510_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 10, 42, 4, 475035, tzinfo=utc), verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='applybuymaterialprocess',
            name='material_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='work.MaterialRecord', verbose_name='\u8017\u6750\u540d\u79f0'),
        ),
    ]
