# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-11 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0030_auto_20240510_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmaterial',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u5165\u5e93\u65f6\u95f4'),
        ),
    ]
