# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-05-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0032_applymaterial_material_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymaterial',
            name='buy_material_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flow.ApplyBuyMaterialProcess', verbose_name='\u8017\u6750\u8d2d\u4e70\u6d41\u7a0b'),
        ),
    ]
